name: AltTabPersonal
options:
  bundleIdPrefix: online.plner
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
targets:
  AltTabPersonal:
    type: application
    platform: macOS
    sources:
      - Sources
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        GENERATE_INFOPLIST_FILE: NO
        PRODUCT_BUNDLE_IDENTIFIER: online.plner.alttab-personal
        PRODUCT_NAME: AltTabPersonal
        SWIFT_VERSION: "5.9"
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        ENABLE_HARDENED_RUNTIME: NO
        COMBINE_HIDPI_IMAGES: YES
schemes:
  AltTabPersonal:
    build:
      targets:
        AltTabPersonal: all
